# credits to zxvnme and danielkrupinski for their packing tool and interesting ideas in zgui
# credits to otvv for inspiration from his FGUI framework
# credits to ocornut's Dear ImGui for awesome ideas, examples, and concepts presented im ImGui
# :)

import glob
import os
import re
import shutil

ignored_files = ['main.cpp', 'd3d9_render.cpp', 'd3d9_render.hpp']
output_contents = []

watermark = """//   _____   ______    _____   _    _   _____ 
//  / ____| |  ____|  / ____| | |  | | |_   _|
// | (___   | |__    | (___   | |  | |   | |  
//  \___ \  |  __|    \___ \  | |  | |   | |  
//  ____) | | |____   ____) | | |__| |  _| |_ 
// |_____/  |______| |_____/   \____/  |_____|
//	
//	File generated by SESUI packer
//	(c) sesame 2020
"""

output_contents.append(watermark)
output_contents.append("#include \"sesui.hpp\"")

for filename in glob.iglob('src/sesui/**/*.cpp', recursive=True):
	if os.path.split(filename)[1] not in ignored_files:
		with open(filename, 'r') as file:
			output_contents.append(re.sub(r'(?s)^//sesui_packer:ignore.*//sesui_packer:resume$', '', file.read(), flags=re.M))

if not os.path.exists('dst'):
	os.mkdir('dst')

shutil.copy('src/sesui/sesui.hpp', 'dst/sesui.hpp')

with open('dst/sesui.cpp', 'w') as output:
	output.write('\n'.join(output_contents))
	
print("\nDone.\n")